-- First, remove the table if it exists
drop table if exists bookmarks;

-- Create the table anew
create table bookmarks ( 
    id INTEGER primary key generated by default as identity,
    title text NOT NULL,
    url text NOT NULL,
    description text,
    rating INTEGER default 1
  )

-- insert some test data
-- Using a multi-row insert statement here
INSERT INTO bookmarks (id, title, url, description, rating)
values
    (1, 'Thinkful', 'https://www.thinkful.com/', 'Online learning built to get you a high-paying job in tech.', 5),
    (2, 'Github', 'https://www.github.com/', 'GitHub is built for collaboration.', 4),
    (3, 'CodeSandbox', 'https://www.codesandbox.com/', 'Play with code.', 3)

    